/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AAvatar: typeof import('ant-design-vue/es')['Avatar']
    AButton: typeof import('ant-design-vue/es')['Button']
    ACard: typeof import('ant-design-vue/es')['Card']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADrawer: typeof import('ant-design-vue/es')['Drawer']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AImage: typeof import('ant-design-vue/es')['Image']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputNumber: typeof import('ant-design-vue/es')['InputNumber']
    AInputPassword: typeof import('ant-design-vue/es')['InputPassword']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuDivider: typeof import('ant-design-vue/es')['MenuDivider']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    AModal: typeof import('ant-design-vue/es')['Modal']
    AProgress: typeof import('ant-design-vue/es')['Progress']
    ARadioButton: typeof import('ant-design-vue/es')['RadioButton']
    ARadioGroup: typeof import('ant-design-vue/es')['RadioGroup']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASelectOption: typeof import('ant-design-vue/es')['SelectOption']
    ASlider: typeof import('ant-design-vue/es')['Slider']
    ASpin: typeof import('ant-design-vue/es')['Spin']
    ATextarea: typeof import('ant-design-vue/es')['Textarea']
    AUploadDragger: typeof import('ant-design-vue/es')['UploadDragger']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    LazyVideo: typeof import('./src/components/LazyVideo.vue')['default']
    MobileTabbar: typeof import('./src/components/MobileTabbar.vue')['default']
    MySubmissionsPanel: typeof import('./src/components/MySubmissionsPanel.vue')['default']
    OverflowScrollRail: typeof import('./src/components/OverflowScrollRail.vue')['default']
    PagedNavigation: typeof import('./src/components/PagedNavigation.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TaskDetailModal: typeof import('./src/components/TaskDetailModal.vue')['default']
    TaskProgress: typeof import('./src/components/TaskProgress.vue')['default']
    TemplateApplyWorkbenchHost: typeof import('./src/components/template-apply/TemplateApplyWorkbenchHost.vue')['default']
    TemplateFaceSwapPanel: typeof import('./src/components/template-apply/TemplateFaceSwapPanel.vue')['default']
    TemplateImagePromptPanel: typeof import('./src/components/template-apply/TemplateImagePromptPanel.vue')['default']
    TemplateImageToVideoPanel: typeof import('./src/components/template-apply/TemplateImageToVideoPanel.vue')['default']
    TemplateVideoSwapPanel: typeof import('./src/components/template-apply/TemplateVideoSwapPanel.vue')['default']
  }
}
