[prompts]
; 基础功能提示词
undress = 给她的衣服脱掉，赤身裸体,露出质感自然的乳房和奶头和乳晕，完全展现她的身体曲线和隐私部位，私处肤色自然且有微微色素沉积，保持面部五官完全一致，不改变动作、身材、脸型、发型、表情和肤色。照片要能完整的看到身体跟头部，分辨率不够的时候，就把整体缩小，一定要保持能看到全貌。
face_swap = 头身互换：以图片1为基准图像，保留其光照、环境及背景。完全移除图片1中的头部，并替换为图片2的头部，严格保留图片2的发型、瞳孔颜色及鼻部结构。复制图片1的眼睛朝向、头部旋转角度及微表情。高清画质，锐利细节，4K分辨率
masturbation = 让图片中的人物赤身裸体，露出乳房，注意不要太夸张，双腿叉开，对着镜头露出私处，阴道微张，阴毛稀疏不要太长，遍布三角区域，小穴流出一些白色半透明的粘稠体液，私处不要粉色的动漫感，要真实的成年女性私处，稍微偏褐色。自己用手使劲揉捏自己的乳房。照片要能完整的看到身体跟头部，分辨率不够的时候，就把整体缩小，一定要保持能看到全貌；头部最好不要变化，不要改变五官和发型，表情千万不要动，嘴巴不要张开
penetration = 让图片中的人物赤身裸体，露出乳房，注意不要太夸张，双腿叉开，对着镜头露出私处，阴道微张，阴毛稀疏不要太长，遍布三角区域，小穴流出一些白色半透明的粘稠体液，私处不要粉色的动漫感，要真实的成年女性私处，稍微偏褐色。自己用手使劲揉捏自己的乳房。第二张图片中的阴茎插入小穴中；头部最好不要变化，不要改变五官和发型，表情千万不要动，嘴巴不要张开

; 视频生成提示词
blowjob = 图中的人往下扒衣服，漏出乳房，注意不要太夸张。一个黑人从左边漏出阴茎，图中的人用手握住他的阴茎，同时用嘴进行口交。注意脸部不要有变化
undress_tongue = 女人往下扒衣服，漏出胸脯和奶头，妖娆的吐出舌头，口水滴下，并且开始翻白眼，阿颜黑
doggy_style = 女人快速脱掉身上所有衣服，清晰的露出奶子和阴部，浑身赤裸，她朝向右侧趴下，翘起屁股，四肢趴地，始终看着镜头。左侧出现一名裸体男子，他握着勃起的阴茎，随后阴茎缓缓插入女子的阴道（侧视图）。
closeup_blowjob = 0-1秒：女性直视镜头，往下扒衣服，漏出乳房，注意不要太夸张；1-2秒：突然脱光衣服，一丝不挂，张大嘴巴，伸出舌头；2-3秒：POV高角度拍摄，双手紧紧抓住她的脸颊，强迫她口交；3-4秒：一根粗硬的阴茎快速而猛烈地在她口中抽插，喷射出液体，节奏疯狂，镜头随着口交的特写镜头而晃动；4-5秒：女性忍不住痛苦嘔吐出來。
perfect_video_insert = 女人快速脱掉身上所有衣服，清晰的露出奶子和阴部，浑身赤裸，女子快速躺下，双腿分开，女人始终看向镜头；一名男子从下方探入。他握着勃起的阴茎，缓缓插入她阴道。
custom_video = 

; 通用负面提示词
negative_prompt = low quality, bad anatomy, ugly, deformed, blurry, watermark, text, bad hands, missing fingers, extra digits
