version: '3.8'

services:
  api-test:
    build: .
    container_name: central-api-test
    ports:
      - "8004:8003"
    env_file:
      - ../.env.test
    environment:
      - TZ=Asia/Shanghai
      - REDIS_URL=redis://:redispassword@host.docker.internal:6379/4
    volumes:
      - ./workflows:/app/workflows
      - ./app:/app/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
