from typing import Any, Optional, Tuple

from src.constants import MODE_IMAGE_TO_VIDEO
from src.services.wan22_aio_video_generation import (
    process_legacy_image_to_video_generation_task,
)


async def process_image_to_video_generation_task(
    *,
    context: Any,
    chat_id: int,
    user_id: int,
    username: str,
    prompt: str,
    images: list[str],
    resolution: Any = None,
    duration: Any = None,
    negative_prompt: str | None = None,
    use_end_frame: bool | None = None,
    resolution_preset: str | None = None,
    wan22_prev_task_id: str | None = None,
    wan22_chain_task_ids: Any = None,
    result_meta: dict[str, Any] | None = None,
    display_mode_name_override: str | None = None,
    status_msg_id: int = None,
    delete_status: bool = True,
    task_type: str = MODE_IMAGE_TO_VIDEO,
    cleanup: bool = True,
    send_result: bool = True,
    deduct_quota: bool = True,
    cost_override: int | None = None,
    reply_markup: Any = None,
    lora_name: str = None,
    lora_strength: float = 1.0,
    lora_items: list[dict[str, Any]] | None = None,
    allow_contribute: bool = True,
    source_post_id: Optional[int] = None,
    base_priority: int = 0,
    allow_cancel: bool = True,
    show_queue_status: bool = True,
    user_cancel_allowed: bool = True,
) -> Tuple[Optional[bytes], Optional[str]]:
    return await process_legacy_image_to_video_generation_task(
        context=context,
        chat_id=chat_id,
        user_id=user_id,
        username=username,
        prompt=prompt,
        images=images,
        resolution=resolution,
        duration=duration,
        negative_prompt=negative_prompt,
        use_end_frame=use_end_frame,
        resolution_preset=resolution_preset,
        wan22_prev_task_id=wan22_prev_task_id,
        wan22_chain_task_ids=wan22_chain_task_ids,
        result_meta=result_meta,
        display_mode_name_override=display_mode_name_override,
        status_msg_id=status_msg_id,
        delete_status=delete_status,
        task_type=task_type,
        cleanup=cleanup,
        send_result=send_result,
        deduct_quota=deduct_quota,
        cost_override=cost_override,
        reply_markup=reply_markup,
        lora_name=lora_name,
        lora_strength=lora_strength,
        lora_items=lora_items,
        allow_contribute=allow_contribute,
        source_post_id=source_post_id,
        base_priority=base_priority,
        allow_cancel=allow_cancel,
        show_queue_status=show_queue_status,
        user_cancel_allowed=user_cancel_allowed,
    )
