from typing import Any, Optional, Tuple

from src.constants import MODE_WAN22_VIDEO_V2
from src.domain_config.wan22_aio_video import (
    DEFAULT_WAN22_VIDEO_V2_NEGATIVE_PROMPT,
    WAN22_VIDEO_V2_DEFAULT_RESOLUTION_PRESET,
    WAN22_VIDEO_V2_DEFAULT_DURATION_SECONDS,
    WAN22_VIDEO_V2_DURATION_SECONDS,
    WAN22_VIDEO_V2_MODEL_PROFILE,
    WAN22_VIDEO_V2_RESOLUTION_PRESETS,
    build_wan22_aio_video_result_meta,
    get_wan22_video_v2_cost,
    get_wan22_video_v2_duration_label,
    get_wan22_video_v2_duration_multiplier_label,
    get_wan22_video_v2_frame_count,
    get_wan22_video_v2_resolution_display,
    get_wan22_video_v2_resolution_label,
    normalize_wan22_video_v2_chain_task_ids,
    normalize_wan22_video_v2_duration_seconds,
    normalize_wan22_video_v2_negative_prompt,
    normalize_wan22_video_v2_resolution_preset,
)
from src.services.wan22_aio_video_generation import (
    process_wan22_video_v2_aio_generation_task,
)

__all__ = [
    "DEFAULT_WAN22_VIDEO_V2_NEGATIVE_PROMPT",
    "WAN22_VIDEO_V2_DEFAULT_DURATION_SECONDS",
    "WAN22_VIDEO_V2_DEFAULT_RESOLUTION_PRESET",
    "WAN22_VIDEO_V2_DURATION_SECONDS",
    "WAN22_VIDEO_V2_RESOLUTION_PRESETS",
    "build_wan22_video_v2_result_meta",
    "get_wan22_video_v2_cost",
    "get_wan22_video_v2_duration_label",
    "get_wan22_video_v2_duration_multiplier_label",
    "get_wan22_video_v2_frame_count",
    "get_wan22_video_v2_resolution_display",
    "get_wan22_video_v2_resolution_label",
    "normalize_wan22_video_v2_chain_task_ids",
    "normalize_wan22_video_v2_duration_seconds",
    "normalize_wan22_video_v2_negative_prompt",
    "normalize_wan22_video_v2_resolution_preset",
    "process_wan22_video_v2_generation_task",
]


def build_wan22_video_v2_result_meta(
    *,
    resolution_preset: str | None,
    negative_prompt: str | None,
    use_end_frame: bool,
    duration_seconds: Any = None,
    prev_task_id: str | None = None,
    chain_task_ids: Any = None,
) -> dict[str, Any]:
    return build_wan22_aio_video_result_meta(
        profile=WAN22_VIDEO_V2_MODEL_PROFILE,
        resolution_preset=resolution_preset,
        duration_seconds=duration_seconds,
        negative_prompt=negative_prompt,
        use_end_frame=use_end_frame,
        prev_task_id=prev_task_id,
        chain_task_ids=chain_task_ids,
    )


async def process_wan22_video_v2_generation_task(
    *,
    context: Any,
    chat_id: int,
    user_id: int,
    username: str,
    prompt: str,
    negative_prompt: str,
    images: list[str],
    use_end_frame: bool,
    status_msg_id: int = None,
    delete_status: bool = True,
    task_type: str = MODE_WAN22_VIDEO_V2,
    cleanup: bool = True,
    send_result: bool = True,
    deduct_quota: bool = True,
    reply_markup: Any = None,
    result_meta: dict[str, Any] | None = None,
    display_mode_name_override: str | None = None,
    allow_contribute: bool = True,
    source_post_id: Optional[int] = None,
    resolution_preset: str | None = None,
    duration: Any = None,
    wan22_prev_task_id: str | None = None,
    wan22_chain_task_ids: Any = None,
    base_priority: int = 0,
    allow_cancel: bool = True,
    user_cancel_allowed: bool = True,
) -> Tuple[Optional[bytes], Optional[str]]:
    return await process_wan22_video_v2_aio_generation_task(
        context=context,
        chat_id=chat_id,
        user_id=user_id,
        username=username,
        prompt=prompt,
        negative_prompt=negative_prompt,
        images=images,
        use_end_frame=use_end_frame,
        status_msg_id=status_msg_id,
        delete_status=delete_status,
        task_type=task_type,
        cleanup=cleanup,
        send_result=send_result,
        deduct_quota=deduct_quota,
        reply_markup=reply_markup,
        result_meta=result_meta,
        display_mode_name_override=display_mode_name_override,
        allow_contribute=allow_contribute,
        source_post_id=source_post_id,
        resolution_preset=resolution_preset,
        duration=duration,
        wan22_prev_task_id=wan22_prev_task_id,
        wan22_chain_task_ids=wan22_chain_task_ids,
        base_priority=base_priority,
        allow_cancel=allow_cancel,
        user_cancel_allowed=user_cancel_allowed,
    )
