ARG RUNTIME_BASE_IMAGE
FROM ${RUNTIME_BASE_IMAGE} AS database-migration
ARG ALLBOT_GIT_SHA
COPY src /app/src
COPY alembic.ini /app/alembic.ini
COPY migrations /app/migrations
LABEL org.opencontainers.image.revision=$ALLBOT_GIT_SHA io.allbot.release.module=database-migration
ENTRYPOINT ["alembic"]
CMD ["upgrade", "head"]
