"""Deprecated compatibility layer for the legacy `video_lora_fsm` module.

New code should import and patch `src.handlers.fsm.image_to_video_fsm` directly.
This module is intentionally kept as a thin re-export surface during migration.
"""

from src.handlers.fsm.image_to_video_fsm import (
    VideoLoraState,
    _build_image_request_text,
    _build_lora_selection_keyboard,
    _build_settings_message,
    _build_submit_message,
    _cleanup_context,
    _get_lora_display_name,
    _initialize_video_lora_context,
    _resolve_image_to_video_task_type,
    _send_start_message,
    _start_video_lora_flow,
    cancel_conversation,
    get_image_to_video_fsm_handler,
    get_video_lora_fsm_handler,
    handle_lora_selection,
    logger,
    permission_service,
    process_settings,
    receive_image,
    receive_prompt,
    robust_edit_text,
    robust_reply_text,
    start_custom_video_compat,
    start_image_to_video,
    start_video_lora,
    timeout_conversation,
    unexpected_input,
    is_global_menu_command,
    create_background_task,
    TaskService,
)

# Deprecated compatibility exports. Keep this file free of new logic.
__all__ = [
    "VideoLoraState",
    "_build_image_request_text",
    "_build_lora_selection_keyboard",
    "_build_settings_message",
    "_build_submit_message",
    "_cleanup_context",
    "_get_lora_display_name",
    "_initialize_video_lora_context",
    "_resolve_image_to_video_task_type",
    "_send_start_message",
    "_start_video_lora_flow",
    "cancel_conversation",
    "get_image_to_video_fsm_handler",
    "get_video_lora_fsm_handler",
    "handle_lora_selection",
    "logger",
    "permission_service",
    "process_settings",
    "receive_image",
    "receive_prompt",
    "robust_edit_text",
    "robust_reply_text",
    "start_custom_video_compat",
    "start_image_to_video",
    "start_video_lora",
    "timeout_conversation",
    "unexpected_input",
    "is_global_menu_command",
    "create_background_task",
    "TaskService",
]
