export const TASK_TYPE_LABELS = {
  undress: '快速脱衣',
  video_undress: '视频脱衣',
  face_swap: '快速换脸',
  faceswap_step1: '快速换脸',
  faceswap_step2: '快速换脸',
  random_faceswap: '随机换脸',
  face_show: '动图露奶',
  face_tongue: '动图吐舌',
  fuck: '动图做爱',
  penetration: '快速抽插',
  penetration_step1: '快速抽插',
  penetration_step2: '快速抽插',
  perfect_video_insert: '动图传教士',
  doggy_style: '动图后入',
  blowjob: '口交黑人',
  masturbation: '快速自慰',
  image: '自由P图',
  edit: '自由P图',
  video: '视频生成',
  video_pro: '专业视频',
  custom_video: '自定义视频',
  face_video_step1: '视频换脸',
  face_video_step2: '视频换脸',
  template_contribute: '模板共建',
  undress_tongue: '脱衣吐舌',
  closeup_blowjob: '特写口交',
  txt2img: '文生图',
  text_to_image: '文生图',
  i2i_pro: '幻想换脸',
  i2i_draw: '局部重绘',
  free_edit_v2_5: '自由P图 v2.5',
  pornmaster_flux2_single_edit: '自由P图 v3（单图）',
  pornmaster_flux2_multi_edit: '自由P图 v3（双图）',
  pornmaster_flux2_edit_bf16: '自由P图 v3',
  pornmaster_flux2_multi_edit_bf16: '自由P图 v3（双图 BF16）',
  face_swap_v2: '快速换脸 v2',
  image_to_video: '图生视频执行任务',
  video_insert: '视频插入',
  video_edit: '视频编辑',
  perfect_video_edit: '精准视频编辑',
  txt2video: '文生视频',
  img2img_lora: '图生图(附加模型)',
  video_lora: '图生视频(附加模型)',
  ltx_video: '高级图生视频',
  ltx_video_flf2v: '高级首尾帧视频',
  ltx_video_v2: '高级图生视频 v2',
  ltx_video_v2_flf2v: '高级首尾帧视频 v2',
  ltx_video_v2v_audio: '高级视频转视频（音频）',
  ltx_t2v: '高级文生视频',
  ltx_t2v_ic: '高级文生视频（人物）',
  ltx25_video_upscale: '视频高清放大',
  prompt_optimize: '提示词优化',
  character_reference_build: '人物角色图构建',
  minimax_h3_t2v: '高级图生视频pro · 文生视频',
  minimax_h3_i2v: '高级图生视频pro · 图生视频',
  minimax_h3_flf2v: '高级图生视频pro · 首尾帧视频',
  minimax_h3_ref2v: '高级图生视频pro · 参考图生视频',
  wan22_video_v2: '图生视频 V2',
  scail2_action_transfer: '动作迁移',
  scail2_action_transfer_long: '动作迁移（长视频）',
  scail2_video_replacement: '视频换人',
  scail2_face_swap_v2: '视频换脸 v2',
  unknown: '未知类型',
}

export const TASK_TYPE_OPTIONS = [
  { label: '自定义视频', value: 'custom_video' },
  { label: '高级图生视频', value: 'ltx_video' },
  {
    label: '高级图生视频pro · 图生视频',
    value: 'minimax_h3_t2v,minimax_h3_i2v,minimax_h3_flf2v',
  },
  {
    label: '高级图生视频pro · 参考图生视频',
    value: 'minimax_h3_ref2v',
  },
  { label: '视频换脸', value: 'face_video_step1' },
  { label: '自由P图', value: 'image,edit' },
  { label: '快速换脸', value: 'face_swap' },
  { label: '快速脱衣', value: 'undress' },
  { label: '动图传教士', value: 'perfect_video_insert' },
  { label: '快速自慰', value: 'masturbation' },
  { label: '特写口交', value: 'closeup_blowjob' },
  { label: '动图后入', value: 'doggy_style' },
  { label: '口交黑人', value: 'blowjob' },
  { label: '脱衣吐舌', value: 'undress_tongue' },
  { label: '快速抽插', value: 'penetration' },
  { label: '文生图', value: 'txt2img' },
  { label: '文生图', value: 'text_to_image' },
  { label: '动图做爱', value: 'fuck' },
  { label: '动图露奶', value: 'face_show' },
  { label: '动图吐舌', value: 'face_tongue' },
  { label: '专业视频', value: 'video_pro' },
  { label: '视频脱衣', value: 'video_undress' },
  { label: '随机换脸', value: 'random_faceswap' },
  { label: '视频生成', value: 'video' },
  { label: '图生视频 V2', value: 'wan22_video_v2' },
  { label: '模板共建', value: 'template_contribute' },
  { label: '幻想换脸', value: 'i2i_pro' },
  { label: '局部重绘', value: 'i2i_draw' },
  { label: '图生图(附加模型)', value: 'img2img_lora' },
  { label: '图生视频(附加模型)', value: 'video_lora' },
]

export const TASK_TYPE_COLORS = {
  undress: '#ff7875',
  face_swap: '#40a9ff',
  faceswap_step1: '#40a9ff',
  faceswap_step2: '#40a9ff',
  random_faceswap: '#096dd9',
  face_show: '#9254de',
  face_tongue: '#722ed1',
  fuck: '#eb2f96',
  penetration: '#f759ab',
  penetration_step1: '#f759ab',
  penetration_step2: '#f759ab',
  perfect_video_insert: '#faad14',
  doggy_style: '#d48806',
  blowjob: '#fa541c',
  masturbation: '#ffc069',
  image: '#ffd666',
  edit: '#ffd666',
  video: '#36cfc9',
  video_pro: '#597ef7',
  custom_video: '#13c2c2',
  video_lora: '#2f54eb',
  template_contribute: '#8c8c8c',
  undress_tongue: '#bae637',
  closeup_blowjob: '#ff4d4f',
  txt2img: '#52c41a',
  text_to_image: '#52c41a',
  i2i_pro: '#ff85c0',
  ltx_video: '#722ed1',
  minimax_h3_t2v: '#531dab',
  minimax_h3_i2v: '#531dab',
  minimax_h3_flf2v: '#391085',
  minimax_h3_ref2v: '#9254de',
  wan22_video_v2: '#13c2c2',
  unknown: '#bfbfbf',
}

export const getTaskTypeLabel = (type) => TASK_TYPE_LABELS[type] || type
