CREATE TABLE IF NOT EXISTS observer_group_messages (
    chat_id BIGINT NOT NULL,
    message_id BIGINT NOT NULL,
    thread_id BIGINT,
    chat_title TEXT NOT NULL,
    author_user_id BIGINT,
    author_username TEXT NOT NULL DEFAULT '',
    author_display_name TEXT NOT NULL DEFAULT '',
    content TEXT NOT NULL,
    sent_at TIMESTAMPTZ NOT NULL,
    edited_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (chat_id, message_id)
);

CREATE INDEX IF NOT EXISTS ix_observer_group_messages_sent_at
    ON observer_group_messages (sent_at);
CREATE INDEX IF NOT EXISTS ix_observer_group_messages_chat_sent
    ON observer_group_messages (chat_id, sent_at);

CREATE TABLE IF NOT EXISTS observer_alert_states (
    state_key TEXT PRIMARY KEY,
    payload JSONB NOT NULL DEFAULT '{}'::jsonb,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS observer_report_runs (
    run_key TEXT PRIMARY KEY,
    report_type TEXT NOT NULL,
    period_start TIMESTAMPTZ NOT NULL,
    period_end TIMESTAMPTZ NOT NULL,
    status TEXT NOT NULL CHECK (status IN ('running', 'completed', 'failed')),
    attempts INTEGER NOT NULL DEFAULT 1,
    model_id TEXT,
    content TEXT,
    error TEXT,
    locked_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    completed_at TIMESTAMPTZ,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS ix_observer_report_runs_updated_at
    ON observer_report_runs (updated_at DESC);

CREATE TABLE IF NOT EXISTS observer_runtime_settings (
    singleton BOOLEAN PRIMARY KEY DEFAULT TRUE CHECK (singleton),
    queue_alerts_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    queue_total_pending_threshold INTEGER NOT NULL DEFAULT 20
        CHECK (queue_total_pending_threshold BETWEEN 1 AND 100000),
    queue_type_pending_threshold INTEGER NOT NULL DEFAULT 10
        CHECK (queue_type_pending_threshold BETWEEN 1 AND 100000),
    group_collection_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    daily_reports_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    weekly_reports_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    monthly_reports_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    recipients_initialized BOOLEAN NOT NULL DEFAULT FALSE,
    groups_initialized BOOLEAN NOT NULL DEFAULT FALSE,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE observer_runtime_settings
    ADD COLUMN IF NOT EXISTS queue_total_pending_threshold
    INTEGER NOT NULL DEFAULT 20
    CHECK (queue_total_pending_threshold BETWEEN 1 AND 100000);
ALTER TABLE observer_runtime_settings
    ADD COLUMN IF NOT EXISTS queue_type_pending_threshold
    INTEGER NOT NULL DEFAULT 10
    CHECK (queue_type_pending_threshold BETWEEN 1 AND 100000);

INSERT INTO observer_runtime_settings (singleton)
VALUES (TRUE)
ON CONFLICT (singleton) DO NOTHING;

CREATE TABLE IF NOT EXISTS observer_admin_recipients (
    telegram_user_id BIGINT PRIMARY KEY CHECK (telegram_user_id > 0),
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS observer_authorized_chats (
    chat_id BIGINT PRIMARY KEY,
    label TEXT NOT NULL DEFAULT '',
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS observer_notification_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type TEXT NOT NULL,
    destination_chat_id BIGINT,
    status TEXT NOT NULL CHECK (status IN ('sent', 'failed', 'skipped')),
    content_preview TEXT NOT NULL DEFAULT '',
    error_type TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS ix_observer_notification_logs_created_at
    ON observer_notification_logs (created_at DESC);
