version: '3.8'

services:
  bot-test:
    build: 
      context: ../
      dockerfile: Dockerfile
    container_name: tg-bot-test
    restart: always
    env_file:
      - ../.env
    environment:
      - BOT_TYPE=TEST
      - REDIS_PREFIX=test_bot_
      - ENABLE_PUBLIC_SHARE=false
      - BOT_TOKEN_TEST=8276500658:AAEeN8Lv7JfYqvcRI0rg7gbrvxq1A88GSJA
      - API_BASE=http://host.docker.internal:8003
    volumes:
      - ../logs:/app/logs
    extra_hosts:
      - "host.docker.internal:host-gateway"
    network_mode: "host" # Use host network to easily access 192.168.1.115 services

  payment-api-test:
    build: 
      context: ../
      dockerfile: Dockerfile
    container_name: payment-api-test
    restart: always
    env_file:
      - ../.env
    environment:
      - BOT_TYPE=TEST
      - REDIS_PREFIX=test_bot_
      - BOT_TOKEN=8276500658:AAEeN8Lv7JfYqvcRI0rg7gbrvxq1A88GSJA
    volumes:
      - ../logs:/app/logs
    extra_hosts:
      - "host.docker.internal:host-gateway"
    network_mode: "host"
    command: ["python", "src/payment_api_server.py"]
