version: '3.8'

services:
  bot:
    build: 
      context: ../
      dockerfile: Dockerfile
    container_name: tg-bot
    restart: always
    env_file:
      - ../.env
    environment:
      - TZ=Asia/Shanghai
      - BOT_TYPE=PROD
      - REDIS_PREFIX=prod_bot_
      - API_BASE=http://host.docker.internal:8003
    volumes:
      - ../logs:/app/logs
    extra_hosts:
      - "host.docker.internal:host-gateway"
    network_mode: "host"
