"""add_history_is_visible

Revision ID: 32affcec25b0
Revises: a99e4c08a0aa
Create Date: 2026-05-07 15:43:39.047967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32affcec25b0'
down_revision: Union[str, Sequence[str], None] = 'a99e4c08a0aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('history', sa.Column('is_visible', sa.Boolean(), server_default=sa.text('true'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('history', 'is_visible')
    # ### end Alembic commands ###
