"""Add source to History

Revision ID: 363b5ddbd9b3
Revises: b329bb842bcd
Create Date: 2026-04-19 17:36:23.982049

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "363b5ddbd9b3"
down_revision: Union[str, Sequence[str], None] = "b329bb842bcd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "history",
        sa.Column("source", sa.String(length=20), server_default="bot", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uix_user_post_action", "user_interactions", type_="unique")
    op.drop_column("history", "source")
    # ### end Alembic commands ###
