"""Add index to Referral inviter_id

Revision ID: 4072f222acad
Revises: 363b5ddbd9b3
Create Date: 2026-04-29 08:53:04.220116

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "4072f222acad"
down_revision: Union[str, Sequence[str], None] = "363b5ddbd9b3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_referrals_inviter_id"), "referrals", ["inviter_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_referrals_inviter_id"), table_name="referrals")
    # ### end Alembic commands ###
