"""Add multi-platform login fields

Revision ID: 434435eccec0
Revises: 58be787ce8b2
Create Date: 2026-04-12 14:32:15.520744

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "434435eccec0"
down_revision: Union[str, Sequence[str], None] = "58be787ce8b2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("telegram_id", sa.BigInteger(), nullable=True))
    op.add_column("users", sa.Column("google_id", sa.String(length=255), nullable=True))
    op.add_column("users", sa.Column("email", sa.String(length=255), nullable=True))
    op.add_column(
        "users", sa.Column("hashed_password", sa.String(length=255), nullable=True)
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_google_id"), "users", ["google_id"], unique=True)
    op.create_index(op.f("ix_users_telegram_id"), "users", ["telegram_id"], unique=True)
    # ### end Alembic commands ###

    # --- Custom Migration Logic: Data Backfill and ID Sequence ---
    op.execute("UPDATE users SET telegram_id = id;")

    # Create a sequence for the new internal ID
    op.execute("CREATE SEQUENCE IF NOT EXISTS users_id_seq OWNED BY users.id;")
    op.execute("ALTER TABLE users ALTER COLUMN id SET DEFAULT nextval('users_id_seq');")

    # Set the sequence to a huge value to avoid collision with 10-digit Telegram IDs
    op.execute(
        "SELECT setval('users_id_seq', GREATEST(COALESCE((SELECT MAX(id) FROM users), 0), 10000000000000) + 1);"
    )
    # -------------------------------------------------------------


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_telegram_id"), table_name="users")
    op.drop_index(op.f("ix_users_google_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_column("users", "hashed_password")
    op.drop_column("users", "email")
    op.drop_column("users", "google_id")
    op.drop_column("users", "telegram_id")
    # ### end Alembic commands ###
