"""drop_deprecated_columns_temp_credits

Revision ID: 58be787ce8b2
Revises: d135ac6ee547
Create Date: 2026-04-10 09:23:43.549911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58be787ce8b2'
down_revision: Union[str, Sequence[str], None] = 'd135ac6ee547'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'temp_credits')
    op.drop_column('users', 'temporary_ingot')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('temporary_ingot', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('temp_credits', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
