"""add_password_version_and_username_index

Revision ID: 75c55a00f6c0
Revises: 4072f222acad
Create Date: 2026-04-29 14:47:35.412806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75c55a00f6c0'
down_revision: Union[str, Sequence[str], None] = '4072f222acad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_version', sa.Integer(), server_default='1', nullable=False))
    op.create_index('idx_users_lower_username', 'users', [sa.text('lower((username)::text)')], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_users_lower_username', table_name='users')
    op.drop_column('users', 'password_version')
    # ### end Alembic commands ###
