"""add gallery comments

Revision ID: 86a36381fa4c
Revises: bfd287d977f3
Create Date: 2026-05-16 10:55:02.858254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86a36381fa4c'
down_revision: Union[str, Sequence[str], None] = 'bfd287d977f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gallery_comments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('content', sa.String(length=500), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['gallery_posts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_gallery_comments_post_created_at', 'gallery_comments', ['post_id', 'created_at'], unique=False)
    op.create_index(
        'ix_gallery_comments_active_post_created_at',
        'gallery_comments',
        ['post_id', 'created_at'],
        unique=False,
        postgresql_where=sa.text('is_active = true'),
    )
    op.create_index(op.f('ix_gallery_comments_user_id'), 'gallery_comments', ['user_id'], unique=False)
    op.add_column('gallery_posts', sa.Column('comments_count', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gallery_posts', 'comments_count')
    op.drop_index('ix_gallery_comments_active_post_created_at', table_name='gallery_comments')
    op.drop_index('ix_gallery_comments_post_created_at', table_name='gallery_comments')
    op.drop_index(op.f('ix_gallery_comments_user_id'), table_name='gallery_comments')
    op.drop_table('gallery_comments')
    # ### end Alembic commands ###
