"""add is_favorited to history

Revision ID: a99e4c08a0aa
Revises: 2028e778563b
Create Date: 2026-05-06 14:40:22.384308

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a99e4c08a0aa"
down_revision: Union[str, Sequence[str], None] = "2028e778563b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("history", sa.Column("is_favorited", sa.Boolean(), nullable=True))
    op.create_index(
        "idx_history_user_favorite",
        "history",
        ["user_id", "is_favorited"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_history_user_favorite", table_name="history")
    op.drop_column("history", "is_favorited")
    # ### end Alembic commands ###
