"""Add allow_contribute to History

Revision ID: b329bb842bcd
Revises: bea1e336a990
Create Date: 2026-04-19 17:26:28.449972

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b329bb842bcd"
down_revision: Union[str, Sequence[str], None] = "bea1e336a990"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("history", sa.Column("allow_contribute", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uix_user_post_action", "user_interactions", type_="unique")
    op.drop_column("history", "allow_contribute")
    # ### end Alembic commands ###
