"""add telegram_file_id to gallery_posts

Revision ID: bea1e336a990
Revises: 0cbec56b4d7d
Create Date: 2026-04-15 21:46:16.453173

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bea1e336a990"
down_revision: Union[str, Sequence[str], None] = "0cbec56b4d7d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "gallery_posts",
        sa.Column("telegram_file_id", sa.String(length=255), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("gallery_posts", "telegram_file_id")
    # ### end Alembic commands ###
