"""initial_baseline

Revision ID: d135ac6ee547
Revises:
Create Date: 2026-04-09 09:42:35.042960

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d135ac6ee547"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP VIEW IF EXISTS v_migration_summary CASCADE")
    op.drop_table("migration_summary_table")
    op.drop_table("discount_rules")
    op.drop_index(op.f("ix_conversations_user_id"), table_name="conversations")
    op.drop_table("conversations")
    op.drop_table("upload_fail_log")
    op.drop_index(op.f("sqlite_autoindex_permissions_1"), table_name="permissions")
    op.drop_table("permissions")
    op.drop_table("file_checksum")
    op.drop_table("migrate_error_log")
    op.drop_table("session_states")
    op.alter_column(
        "checkin_history",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "history",
        "task_id",
        existing_type=sa.TEXT(),
        type_=sa.String(length=64),
        existing_nullable=True,
    )
    op.alter_column(
        "history",
        "type",
        existing_type=sa.TEXT(),
        type_=sa.String(length=20),
        existing_nullable=True,
    )
    op.alter_column(
        "history",
        "input_file",
        existing_type=sa.TEXT(),
        type_=sa.Text(),
        existing_nullable=True,
    )
    op.alter_column(
        "history",
        "output_file",
        existing_type=sa.TEXT(),
        type_=sa.Text(),
        existing_nullable=True,
    )
    op.alter_column(
        "history",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=True,
    )
    op.create_foreign_key(None, "orders", "users", ["telegram_id"], ["id"])
    op.create_foreign_key(None, "orders", "membership_plans", ["plan_id"], ["id"])
    op.alter_column(
        "referrals",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=True,
    )
    op.drop_index(op.f("sqlite_autoindex_referrals_1"), table_name="referrals")
    op.create_unique_constraint(None, "referrals", ["invitee_id"])
    op.alter_column(
        "template_contributions",
        "file_path",
        existing_type=sa.TEXT(),
        type_=sa.String(length=255),
        existing_nullable=False,
    )
    op.alter_column(
        "template_contributions",
        "file_type",
        existing_type=sa.TEXT(),
        type_=sa.String(length=20),
        existing_nullable=True,
    )
    op.alter_column(
        "template_contributions",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=True,
    )
    op.alter_column(
        "user_logs",
        "username",
        existing_type=sa.TEXT(),
        type_=sa.String(length=100),
        existing_nullable=True,
    )
    op.alter_column(
        "user_logs",
        "operation_type",
        existing_type=sa.TEXT(),
        type_=sa.String(length=50),
        existing_nullable=False,
    )
    op.alter_column(
        "user_logs",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=True,
    )
    op.alter_column(
        "users",
        "username",
        existing_type=sa.TEXT(),
        type_=sa.String(length=100),
        existing_nullable=True,
    )
    op.alter_column(
        "users",
        "full_name",
        existing_type=sa.TEXT(),
        type_=sa.String(length=200),
        existing_nullable=True,
    )
    op.alter_column(
        "users",
        "user_group",
        existing_type=sa.TEXT(),
        type_=sa.String(length=20),
        existing_nullable=True,
        existing_server_default=sa.text("'游客'::text"),
    )
    op.alter_column(
        "users",
        "last_activity",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=True,
    )
    op.alter_column(
        "users",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=True,
    )
    op.drop_column("users", "is_first_charge")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "is_first_charge",
            sa.BOOLEAN(),
            server_default=sa.text("true"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.alter_column(
        "users",
        "created_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=True,
    )
    op.alter_column(
        "users",
        "last_activity",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=True,
    )
    op.alter_column(
        "users",
        "user_group",
        existing_type=sa.String(length=20),
        type_=sa.TEXT(),
        existing_nullable=True,
        existing_server_default=sa.text("'游客'::text"),
    )
    op.alter_column(
        "users",
        "full_name",
        existing_type=sa.String(length=200),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.alter_column(
        "users",
        "username",
        existing_type=sa.String(length=100),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.alter_column(
        "user_logs",
        "created_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=True,
    )
    op.alter_column(
        "user_logs",
        "operation_type",
        existing_type=sa.String(length=50),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.alter_column(
        "user_logs",
        "username",
        existing_type=sa.String(length=100),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.alter_column(
        "template_contributions",
        "created_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=True,
    )
    op.alter_column(
        "template_contributions",
        "file_type",
        existing_type=sa.String(length=20),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.alter_column(
        "template_contributions",
        "file_path",
        existing_type=sa.String(length=255),
        type_=sa.TEXT(),
        existing_nullable=False,
    )
    op.drop_constraint(None, "referrals", type_="unique")
    op.create_index(
        op.f("sqlite_autoindex_referrals_1"), "referrals", ["invitee_id"], unique=True
    )
    op.alter_column(
        "referrals",
        "created_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=True,
    )
    op.drop_constraint(None, "orders", type_="foreignkey")
    op.drop_constraint(None, "orders", type_="foreignkey")
    op.alter_column(
        "history",
        "created_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=True,
    )
    op.alter_column(
        "history",
        "output_file",
        existing_type=sa.String(length=255),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.alter_column(
        "history",
        "input_file",
        existing_type=sa.String(length=255),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.alter_column(
        "history",
        "type",
        existing_type=sa.String(length=20),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.alter_column(
        "history",
        "task_id",
        existing_type=sa.String(length=64),
        type_=sa.TEXT(),
        existing_nullable=True,
    )
    op.alter_column(
        "checkin_history",
        "created_at",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.create_table(
        "session_states",
        sa.Column("user_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("state", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("context_data", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("session_states_pkey")),
    )
    op.create_table(
        "migrate_error_log",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("table_name", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("batch_range", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("error_message", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "failed_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("migrate_error_log_pkey")),
    )
    op.create_table(
        "file_checksum",
        sa.Column(
            "file_path", sa.VARCHAR(length=512), autoincrement=False, nullable=False
        ),
        sa.Column("md5", sa.VARCHAR(length=32), autoincrement=False, nullable=True),
        sa.Column("size", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column(
            "uploaded_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("file_path", name=op.f("file_checksum_pkey")),
    )
    op.create_table(
        "permissions",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("entity_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("type", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("permissions_pkey")),
    )
    op.create_index(
        op.f("sqlite_autoindex_permissions_1"),
        "permissions",
        ["entity_id"],
        unique=True,
    )
    op.create_table(
        "upload_fail_log",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("file_path", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("error_message", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "failed_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("upload_fail_log_pkey")),
    )
    op.create_table(
        "conversations",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("role", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("content", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("conversations_user_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("conversations_pkey")),
    )
    op.create_index(
        op.f("ix_conversations_user_id"), "conversations", ["user_id"], unique=False
    )
    op.create_table(
        "discount_rules",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "rule_type", sa.VARCHAR(length=50), autoincrement=False, nullable=False
        ),
        sa.Column(
            "target_level", sa.VARCHAR(length=50), autoincrement=False, nullable=True
        ),
        sa.Column(
            "discount_rate",
            sa.NUMERIC(precision=3, scale=2),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("is_active", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("discount_rules_pkey")),
    )
    op.create_table(
        "migration_summary_table",
        sa.Column("table_name", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("source_rows", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("target_rows", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("duration_seconds", sa.NUMERIC(), autoincrement=False, nullable=True),
        sa.Column("status", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("validation_result", sa.TEXT(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint(
            "table_name", name=op.f("migration_summary_table_pkey")
        ),
    )
    # ### end Alembic commands ###
