from src.constants import (
    MODE_BLOWJOB,
    MODE_CLOSEUP_BLOWJOB,
    MODE_CUSTOM_VIDEO,
    MODE_DOGGY_STYLE,
    MODE_EDIT,
    MODE_FACE_VIDEO_STEP1,
    MODE_FACE_VIDEO_STEP2,
    MODE_FACESWAP_STEP1,
    MODE_FACESWAP_STEP2,
    MODE_IMAGE_TO_VIDEO,
    MODE_IMG2IMG_LORA,
    MODE_I2I_DRAW,
    MODE_I2I_PRO,
    MODE_LTX_VIDEO,
    MODE_MASTURBATION,
    MODE_PERFECT_VIDEO_INSERT,
    MODE_PENETRATION_STEP1,
    MODE_PENETRATION_STEP2,
    MODE_PORNMASTER_FLUX2_MULTI_EDIT,
    MODE_PORNMASTER_FLUX2_SINGLE_EDIT,
    MODE_RANDOM_FACESWAP,
    MODE_SCAIL2_ACTION_TRANSFER,
    MODE_SCAIL2_ACTION_TRANSFER_LONG,
    MODE_SCAIL2_FACE_SWAP_V2,
    MODE_SCAIL2_VIDEO_REPLACEMENT,
    MODE_TXT2IMG,
    MODE_UNDRESS,
    MODE_UNDRESS_TONGUE,
    MODE_WAN22_VIDEO_V2,
)

EXECUTION_TASK_TYPE_IMG2IMG = "img2img"
EXECUTION_TASK_TYPE_FACE_SWAP = "face_swap"
EXECUTION_TASK_TYPE_FACE_VIDEO = "face_video"
EXECUTION_TASK_TYPE_IMAGE_TO_VIDEO = "image_to_video"
EXECUTION_TASK_TYPE_TEXT_TO_IMAGE = "t2i-pornmaster-turbo"
EXECUTION_TASK_TYPE_VIDEO_EDIT = "video_edit"
EXECUTION_TASK_TYPE_VIDEO_INSERT = "video_insert"

_IMG2IMG_PUBLIC_TASK_TYPES = {
    "image",
    "quick_image",
    MODE_EDIT,
    MODE_UNDRESS,
    MODE_MASTURBATION,
    MODE_RANDOM_FACESWAP,
    MODE_PENETRATION_STEP1,
    MODE_PENETRATION_STEP2,
}
_FACE_SWAP_PUBLIC_TASK_TYPES = {
    EXECUTION_TASK_TYPE_FACE_SWAP,
    MODE_FACESWAP_STEP1,
    MODE_FACESWAP_STEP2,
}
_FACE_VIDEO_PUBLIC_TASK_TYPES = {
    EXECUTION_TASK_TYPE_FACE_VIDEO,
    MODE_FACE_VIDEO_STEP1,
    MODE_FACE_VIDEO_STEP2,
}
_IMAGE_TO_VIDEO_PUBLIC_TASK_TYPES = {
    MODE_CUSTOM_VIDEO,
    MODE_IMAGE_TO_VIDEO,
    "image_to_video",
}
_VIDEO_EDIT_PUBLIC_TASK_TYPES = {
    "perfect_video_edit",
    "txt2video",
    MODE_PERFECT_VIDEO_INSERT,
    MODE_BLOWJOB,
    MODE_UNDRESS_TONGUE,
    MODE_CLOSEUP_BLOWJOB,
}
_VIDEO_INSERT_PUBLIC_TASK_TYPES = {
    MODE_DOGGY_STYLE,
}

_WORKER_EXECUTION_TASK_TYPE_ALIASES = {
    **dict.fromkeys(_IMG2IMG_PUBLIC_TASK_TYPES, EXECUTION_TASK_TYPE_IMG2IMG),
    **dict.fromkeys(_FACE_SWAP_PUBLIC_TASK_TYPES, EXECUTION_TASK_TYPE_FACE_SWAP),
    **dict.fromkeys(_FACE_VIDEO_PUBLIC_TASK_TYPES, EXECUTION_TASK_TYPE_FACE_VIDEO),
    **dict.fromkeys(
        _IMAGE_TO_VIDEO_PUBLIC_TASK_TYPES,
        EXECUTION_TASK_TYPE_IMAGE_TO_VIDEO,
    ),
    **dict.fromkeys(_VIDEO_EDIT_PUBLIC_TASK_TYPES, EXECUTION_TASK_TYPE_IMAGE_TO_VIDEO),
    **dict.fromkeys(_VIDEO_INSERT_PUBLIC_TASK_TYPES, EXECUTION_TASK_TYPE_IMAGE_TO_VIDEO),
    MODE_TXT2IMG: EXECUTION_TASK_TYPE_TEXT_TO_IMAGE,
    MODE_IMG2IMG_LORA: MODE_IMG2IMG_LORA,
    MODE_I2I_PRO: MODE_I2I_PRO,
    MODE_I2I_DRAW: MODE_I2I_DRAW,
    MODE_PORNMASTER_FLUX2_SINGLE_EDIT: MODE_PORNMASTER_FLUX2_SINGLE_EDIT,
    MODE_PORNMASTER_FLUX2_MULTI_EDIT: MODE_PORNMASTER_FLUX2_MULTI_EDIT,
    MODE_LTX_VIDEO: MODE_LTX_VIDEO,
    MODE_WAN22_VIDEO_V2: MODE_WAN22_VIDEO_V2,
    MODE_SCAIL2_ACTION_TRANSFER: MODE_SCAIL2_ACTION_TRANSFER,
    MODE_SCAIL2_ACTION_TRANSFER_LONG: MODE_SCAIL2_ACTION_TRANSFER_LONG,
    MODE_SCAIL2_VIDEO_REPLACEMENT: MODE_SCAIL2_VIDEO_REPLACEMENT,
    MODE_SCAIL2_FACE_SWAP_V2: MODE_SCAIL2_FACE_SWAP_V2,
    EXECUTION_TASK_TYPE_VIDEO_EDIT: EXECUTION_TASK_TYPE_IMAGE_TO_VIDEO,
    EXECUTION_TASK_TYPE_VIDEO_INSERT: EXECUTION_TASK_TYPE_IMAGE_TO_VIDEO,
}


def resolve_worker_execution_task_type(task_type: str | None) -> str:
    raw_task_type = str(task_type or "").strip()
    if not raw_task_type:
        return "unknown"
    return _WORKER_EXECUTION_TASK_TYPE_ALIASES.get(raw_task_type, raw_task_type)
