#!/usr/bin/env python3
"""Generate the frontend's read-only task contract from the Python registry."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys


REPOSITORY_ROOT = Path(__file__).resolve().parents[1]
FRONTEND_CONTRACT_PATH = (
    REPOSITORY_ROOT / "frontend/src/generated/taskTypeContract.ts"
)


def _typescript_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def render_frontend_task_type_contract() -> str:
    if str(REPOSITORY_ROOT) not in sys.path:
        sys.path.insert(0, str(REPOSITORY_ROOT))

    from src.domain_config.task_type_registry import TASK_TYPE_REGISTRY

    lines = [
        "// Generated by scripts/generate_task_type_contract.py. Do not edit manually.",
        "// The Python task registry is the only source of truth.",
        "",
        "export const TASK_TYPE_CONTRACT = {",
    ]
    for task_type, entry in sorted(TASK_TYPE_REGISTRY.items()):
        fields = [
            f"publicType: {_typescript_string(entry.public_type)}",
            f"isGeneration: {str(entry.is_generation).lower()}",
            f"isVideo: {str(entry.is_video).lower()}",
            f"gallerySupported: {str(entry.gallery_supported).lower()}",
            (
                "applyInputReuseSupported: "
                f"{str(entry.apply_input_reuse_supported).lower()}"
            ),
            f"cost: {entry.cost if entry.cost is not None else 'null'}",
        ]
        lines.append(
            f"  {_typescript_string(task_type)}: {{ {', '.join(fields)} }},"
        )
    lines.extend(
        [
            "} as const",
            "",
            "export type TaskTypeId = keyof typeof TASK_TYPE_CONTRACT",
            "",
            "export function isTaskTypeId(value: string): value is TaskTypeId {",
            "  return Object.prototype.hasOwnProperty.call(TASK_TYPE_CONTRACT, value)",
            "}",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--check", action="store_true")
    mode.add_argument("--write", action="store_true")
    args = parser.parse_args()

    expected = render_frontend_task_type_contract()
    if args.write:
        FRONTEND_CONTRACT_PATH.parent.mkdir(parents=True, exist_ok=True)
        FRONTEND_CONTRACT_PATH.write_text(expected, encoding="utf-8")
        return 0

    actual = (
        FRONTEND_CONTRACT_PATH.read_text(encoding="utf-8")
        if FRONTEND_CONTRACT_PATH.exists()
        else ""
    )
    if actual != expected:
        print(
            "frontend task type contract is stale; run "
            "python scripts/generate_task_type_contract.py --write",
            file=sys.stderr,
        )
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
